### ISSUE TITLE
start is not defined

### ISSUE THREAD

**Issue by kalepail** [AggressivelyMeows/cfw-easy-utils#2]
Great utility library! Really enjoying it. Had an issue though running `watch.getTotalTime()`

```
start is not defined
```

Probably because `start` here should be `this.start`?
https://github.com/AggressivelyMeows/cfw-easy-utils/blob/main/src/stopwatch.js#L30

**Comment by AggressivelyMeows** [comment]
You are completely correct, sorry for not noticing this bug. All of the demos i've tested just passed the watch object to the response handler that doesnt include that function.

**Comment by AggressivelyMeows** [comment]
Closed due to being fixed in the pull request.
