### ISSUE TITLE
Password functionality

### ISSUE THREAD

**Issue by grantholle** [AggressivelyMeows/cfw-easy-utils#5]
Having the password hashing/checking functionality was really helpful for me!

Quick thought/question... Wouldn't saving the salt phrase along with the hash in the database essentially negate the purpose of hashing? I'm definitely no cryptographer, but that's what it seems like to me.

**Comment by AggressivelyMeows** [comment]
Sorry for not responding earlier, GitHub doesnt want to tell me about notifications for some reason!

Salting is used to combat "Rainbow Tables" which are tables of precalculated hashes for a certain hashing algo. Salts are completely unique per password and make rainbow tables useless by making it so each password would have a different hash than the other, making it so you would have to generate a rainbow table for *every* password in the database. At that point, you would be better off just brute forcing it manually, using up resources per attempt.

or in other words:
> the point of the salt is simply to make it so that one rainbow table can't break every password in the DB.

**Comment by grantholle** [comment]
I see. So having the salt visible/accessible doesn't affect the ability to crack the password?
